### PR TITLE
Add standard lint to pre-commit hook.

### LINKED ISSUE #39: add pre-commit hook to run jslint

### PR DESCRIPTION
**Pull request by clkao**
Closes #39

### CODE REVIEW

**Comment by juliangruber** [comment]
+1 for the lint script, but -1 from me on the pre-commit hook. those just keep annoying me :/

**Comment by clkao** [comment]
Is it the additional stdout being annoying (this can be disabled easily)? or the fact the lint is run during pre-commit?

I found this useful for reducing roundtrips in casual PR not noticing the styles.  Alternatively, we can also add a CI check in github though.

**Comment by juliangruber** [comment]
It's simply that i run `npm test` before committing anyways, so this would be two lint runs

**Comment by clkao** [comment]
Oh this repo has no npm test yet ;)

**Comment by mafintosh** [comment]
i'd add standard as the test script and add travis to this repo. that works quite well.

**Comment by mafintosh** [comment]
and not have the precommit hook. you can have an npm script that sets that up though if it helps your workflow :)

**Comment by clkao** [comment]
ok this is being the sole `npm test` for now, and travis is enabled in my fork: https://travis-ci.org/clkao/hyperdrive-ui/builds/136925488

@karissa can you enable travis-ci in this repo?

**Comment by okdistribute** [comment]
ok activated on travis!

**Pull request merged**
