### PR TITLE
use file tree browser widget

### PR DESCRIPTION
**Pull request by berleant**

### CODE REVIEW

**Comment by okdistribute** [comment]
Are we deprecating this branch in favor of folderListener? if so, we could close this pull request.

**Comment by berleant** [comment]
We can do that. Sorry, still learning github. Wishing we could propose
merges without actually committing them!

**Comment by okdistribute** [comment]
nah its totally fine, we can just delete this branch

**Comment by okdistribute** [comment]
see ^! :)

**Pull request closed without merging**
