### PR TITLE
[PROPOSAL] use yo-yo + minidux to componetize ui

### PR DESCRIPTION
**Pull request by laurengarcia**
this is seriously the coolest thing ever. 
i think we can get away with just using minidux + yo. we don't even need choo from what i can tell!

why this is amazing:
- you can initialize all components with same function signature, no matter what. 
- app.js will not bloat because all components just SUBSCRIBE(!) to state 
- we have elimiated need for events that are related to state. events are now ONLY for user-initiated actions, the way they should be.
- yo does the dom diffing extremely efficiently and we don't need choo (i think)

i can't believe this is possible, i am really really impressed with yo and minidux together. 
have been looking for a lightweight solution like this for a while now. 
++++++ mad props!!!!

### CODE REVIEW

**Comment by juliangruber** [comment]
would you need to use some *dux in order to use this module then? i liked that before you could integrate the module into pretty much anything

**Comment by laurengarcia** [comment]
minidux is internal to this module. so by using this module you are implicitly using minidux.

**Comment by laurengarcia** [comment]
as a consumer of this module, there is nothing that you need to do differently (if that is the question).

**Comment by laurengarcia** [comment]
am closing this here; it actually now belongs in https://github.com/datproject/dat.land

**Pull request closed without merging**
